# Use postgres/example user/password credentials
version: "3"
services:
  db:
    image: postgres:10.3-alpine
    container_name: beeDB
    restart: "no"
    environment:
      POSTGRES_PASSWORD: "2yNm73hUk9yFtJpo"
      POSTGRES_USER: "bot"
    volumes:
      - ./psql/postgresql:/var/lib/postgres
      - ./psql/postgresql_data:/var/lib/postgres/data
    ports:
      - 9876:9876

networks:
  default:
    external:
      name: beeNet

